# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
      - uses: actions/checkout@main
      - name: Set up JDK 25
        uses: actions/setup-java@main
        with:
          java-version: '25'
          distribution: 'temurin'
      - name: Build with Gradle (Linux)
        if: runner.os == 'Linux'
        run: xvfb-run --auto-servernum ./gradlew clean build fatjar
      - name: Build with Gradle
        if: runner.os != 'Linux'
        run: ./gradlew clean build fatjar
      - uses: actions/upload-artifact@main
        with:
          name: ${{ matrix.os }}
          path: app/build/libs
