# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 20
        uses: actions/setup-java@main
        with:
          java-version: '20'
          distribution: 'temurin'
      - name: Build with Gradle
        run: ./gradlew clean build fatjar
      - uses: actions/upload-artifact@main
        with:
          name: Package
          path: app/build/libs
